### ISSUE TITLE
Readme refers to setting that does not exist

### ISSUE THREAD

**Issue by gstamp** [envato/event_sourcery-postgres#34]
The readme refers to the field `use_optimistic_concurrency` however that does not seem to work. It generates the following error:

```
NoMethodError: undefined method `use_optimistic_concurrency=' for #<EventSourcery::Postgres::Config:0x000000017f9b70>
```

**Comment by stevehodgkiss** [comment]
That setting was removed a while ago. We should remove that line from the readme.
